//
// Created by Pablo Deputter on 11/11/2021.
//

#ifndef ADVANCED_PROGRAMMING_DOODLEJUMP_RANDOM_H
#define ADVANCED_PROGRAMMING_DOODLEJUMP_RANDOM_H

class Random
{
};

#endif // ADVANCED_PROGRAMMING_DOODLEJUMP_RANDOM_H
