//
// Created by Pablo Deputter on 13/11/2021.
//

#ifndef ADVANCED_PROGRAMMING_DOODLEJUMP_ENTITY_H
#define ADVANCED_PROGRAMMING_DOODLEJUMP_ENTITY_H

class Entity
{
};

#endif // ADVANCED_PROGRAMMING_DOODLEJUMP_ENTITY_H
